package proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

public interface OrderDetailOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required uint32 order_detail_id = 1;
  /**
   * <code>required uint32 order_detail_id = 1;</code>
   */
  boolean hasOrderDetailId();
  /**
   * <code>required uint32 order_detail_id = 1;</code>
   */
  int getOrderDetailId();

  // required uint32 product_id = 2;
  /**
   * <code>required uint32 product_id = 2;</code>
   */
  boolean hasProductId();
  /**
   * <code>required uint32 product_id = 2;</code>
   */
  int getProductId();
}
