package proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

public interface ProductCheckoutRequestOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required uint32 buyer_id = 1;
  /**
   * <code>required uint32 buyer_id = 1;</code>
   */
  boolean hasBuyerId();
  /**
   * <code>required uint32 buyer_id = 1;</code>
   */
  int getBuyerId();

  // repeated .RequestedProduct requested_product = 2;
  /**
   * <code>repeated .RequestedProduct requested_product = 2;</code>
   */
  java.util.List<RequestedProduct> 
      getRequestedProductList();
  /**
   * <code>repeated .RequestedProduct requested_product = 2;</code>
   */
  RequestedProduct getRequestedProduct(int index);
  /**
   * <code>repeated .RequestedProduct requested_product = 2;</code>
   */
  int getRequestedProductCount();
  /**
   * <code>repeated .RequestedProduct requested_product = 2;</code>
   */
  java.util.List<? extends RequestedProductOrBuilder> 
      getRequestedProductOrBuilderList();
  /**
   * <code>repeated .RequestedProduct requested_product = 2;</code>
   */
  RequestedProductOrBuilder getRequestedProductOrBuilder(
      int index);

  // optional string pci_info = 3;
  /**
   * <code>optional string pci_info = 3;</code>
   */
  boolean hasPciInfo();
  /**
   * <code>optional string pci_info = 3;</code>
   */
  java.lang.String getPciInfo();
  /**
   * <code>optional string pci_info = 3;</code>
   */
  com.google.protobuf.ByteString
      getPciInfoBytes();
}
