// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

public interface CategoryOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required uint64 id = 1;
  /**
   * <code>required uint64 id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>required uint64 id = 1;</code>
   */
  long getId();

  // required string name = 2;
  /**
   * <code>required string name = 2;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  // optional uint64 recommeded_category_id = 3;
  /**
   * <code>optional uint64 recommeded_category_id = 3;</code>
   */
  boolean hasRecommededCategoryId();
  /**
   * <code>optional uint64 recommeded_category_id = 3;</code>
   */
  long getRecommededCategoryId();
}
