// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

public interface OrderDetailOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required uint32 order_detail_id = 1;
  /**
   * <code>required uint32 order_detail_id = 1;</code>
   */
  boolean hasOrderDetailId();
  /**
   * <code>required uint32 order_detail_id = 1;</code>
   */
  int getOrderDetailId();

  // required .Product product = 2;
  /**
   * <code>required .Product product = 2;</code>
   */
  boolean hasProduct();
  /**
   * <code>required .Product product = 2;</code>
   */
  Product getProduct();
  /**
   * <code>required .Product product = 2;</code>
   */
  ProductOrBuilder getProductOrBuilder();
}
