// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

/**
 * Protobuf type {@code OrderDetail}
 */
public  final class OrderDetail extends
    com.google.protobuf.GeneratedMessage
    implements OrderDetailOrBuilder {
  // Use OrderDetail.newBuilder() to construct.
  private OrderDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private OrderDetail(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final OrderDetail defaultInstance;
  public static OrderDetail getDefaultInstance() {
    return defaultInstance;
  }

  public OrderDetail getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private OrderDetail(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            orderDetailId_ = input.readUInt32();
            break;
          }
          case 18: {
            Product.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = product_.toBuilder();
            }
            product_ = input.readMessage(Product.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(product_);
              product_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProductProtos.internal_static_OrderDetail_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProductProtos.internal_static_OrderDetail_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            OrderDetail.class, OrderDetail.Builder.class);
  }

  public static com.google.protobuf.Parser<OrderDetail> PARSER =
      new com.google.protobuf.AbstractParser<OrderDetail>() {
    public OrderDetail parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OrderDetail(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<OrderDetail> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required uint32 order_detail_id = 1;
  public static final int ORDER_DETAIL_ID_FIELD_NUMBER = 1;
  private int orderDetailId_;
  /**
   * <code>required uint32 order_detail_id = 1;</code>
   */
  public boolean hasOrderDetailId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required uint32 order_detail_id = 1;</code>
   */
  public int getOrderDetailId() {
    return orderDetailId_;
  }

  // required .Product product = 2;
  public static final int PRODUCT_FIELD_NUMBER = 2;
  private Product product_;
  /**
   * <code>required .Product product = 2;</code>
   */
  public boolean hasProduct() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required .Product product = 2;</code>
   */
  public Product getProduct() {
    return product_;
  }
  /**
   * <code>required .Product product = 2;</code>
   */
  public ProductOrBuilder getProductOrBuilder() {
    return product_;
  }

  private void initFields() {
    orderDetailId_ = 0;
    product_ = Product.getDefaultInstance();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasOrderDetailId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasProduct()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getProduct().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeUInt32(1, orderDetailId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, product_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, orderDetailId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, product_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static OrderDetail parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static OrderDetail parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static OrderDetail parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static OrderDetail parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static OrderDetail parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static OrderDetail parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static OrderDetail parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static OrderDetail parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static OrderDetail parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static OrderDetail parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(OrderDetail prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code OrderDetail}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements OrderDetailOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProductProtos.internal_static_OrderDetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProductProtos.internal_static_OrderDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OrderDetail.class, OrderDetail.Builder.class);
    }

    // Construct using OrderDetail.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getProductFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      orderDetailId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (productBuilder_ == null) {
        product_ = Product.getDefaultInstance();
      } else {
        productBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProductProtos.internal_static_OrderDetail_descriptor;
    }

    public OrderDetail getDefaultInstanceForType() {
      return OrderDetail.getDefaultInstance();
    }

    public OrderDetail build() {
      OrderDetail result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public OrderDetail buildPartial() {
      OrderDetail result = new OrderDetail(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.orderDetailId_ = orderDetailId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (productBuilder_ == null) {
        result.product_ = product_;
      } else {
        result.product_ = productBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof OrderDetail) {
        return mergeFrom((OrderDetail)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(OrderDetail other) {
      if (other == OrderDetail.getDefaultInstance()) return this;
      if (other.hasOrderDetailId()) {
        setOrderDetailId(other.getOrderDetailId());
      }
      if (other.hasProduct()) {
        mergeProduct(other.getProduct());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasOrderDetailId()) {
        
        return false;
      }
      if (!hasProduct()) {
        
        return false;
      }
      if (!getProduct().isInitialized()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      OrderDetail parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (OrderDetail) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required uint32 order_detail_id = 1;
    private int orderDetailId_ ;
    /**
     * <code>required uint32 order_detail_id = 1;</code>
     */
    public boolean hasOrderDetailId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 order_detail_id = 1;</code>
     */
    public int getOrderDetailId() {
      return orderDetailId_;
    }
    /**
     * <code>required uint32 order_detail_id = 1;</code>
     */
    public Builder setOrderDetailId(int value) {
      bitField0_ |= 0x00000001;
      orderDetailId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint32 order_detail_id = 1;</code>
     */
    public Builder clearOrderDetailId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      orderDetailId_ = 0;
      onChanged();
      return this;
    }

    // required .Product product = 2;
    private Product product_ = Product.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        Product, Product.Builder, ProductOrBuilder> productBuilder_;
    /**
     * <code>required .Product product = 2;</code>
     */
    public boolean hasProduct() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Product product = 2;</code>
     */
    public Product getProduct() {
      if (productBuilder_ == null) {
        return product_;
      } else {
        return productBuilder_.getMessage();
      }
    }
    /**
     * <code>required .Product product = 2;</code>
     */
    public Builder setProduct(Product value) {
      if (productBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        product_ = value;
        onChanged();
      } else {
        productBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .Product product = 2;</code>
     */
    public Builder setProduct(
        Product.Builder builderForValue) {
      if (productBuilder_ == null) {
        product_ = builderForValue.build();
        onChanged();
      } else {
        productBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .Product product = 2;</code>
     */
    public Builder mergeProduct(Product value) {
      if (productBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            product_ != Product.getDefaultInstance()) {
          product_ =
            Product.newBuilder(product_).mergeFrom(value).buildPartial();
        } else {
          product_ = value;
        }
        onChanged();
      } else {
        productBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .Product product = 2;</code>
     */
    public Builder clearProduct() {
      if (productBuilder_ == null) {
        product_ = Product.getDefaultInstance();
        onChanged();
      } else {
        productBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>required .Product product = 2;</code>
     */
    public Product.Builder getProductBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getProductFieldBuilder().getBuilder();
    }
    /**
     * <code>required .Product product = 2;</code>
     */
    public ProductOrBuilder getProductOrBuilder() {
      if (productBuilder_ != null) {
        return productBuilder_.getMessageOrBuilder();
      } else {
        return product_;
      }
    }
    /**
     * <code>required .Product product = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        Product, Product.Builder, ProductOrBuilder> 
        getProductFieldBuilder() {
      if (productBuilder_ == null) {
        productBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            Product, Product.Builder, ProductOrBuilder>(
                product_,
                getParentForChildren(),
                isClean());
        product_ = null;
      }
      return productBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:OrderDetail)
  }

  static {
    defaultInstance = new OrderDetail(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:OrderDetail)
}

