// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

/**
 * Protobuf type {@code Product}
 */
public  final class Product extends
    com.google.protobuf.GeneratedMessage
    implements ProductOrBuilder {
  // Use Product.newBuilder() to construct.
  private Product(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private Product(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final Product defaultInstance;
  public static Product getDefaultInstance() {
    return defaultInstance;
  }

  public Product getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private Product(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            id_ = input.readUInt64();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            name_ = input.readBytes();
            break;
          }
          case 26: {
            Brand.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
              subBuilder = brand_.toBuilder();
            }
            brand_ = input.readMessage(Brand.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(brand_);
              brand_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          case 34: {
            Category.Builder subBuilder = null;
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
              subBuilder = category_.toBuilder();
            }
            category_ = input.readMessage(Category.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(category_);
              category_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000008;
            break;
          }
          case 42: {
            bitField0_ |= 0x00000010;
            color_ = input.readBytes();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000020;
            sellRate_ = input.readUInt64();
            break;
          }
          case 56: {
            bitField0_ |= 0x00000040;
            netRate_ = input.readUInt64();
            break;
          }
          case 64: {
            bitField0_ |= 0x00000080;
            quantity_ = input.readUInt32();
            break;
          }
          case 74: {
            bitField0_ |= 0x00000100;
            description_ = input.readBytes();
            break;
          }
          case 82: {
            bitField0_ |= 0x00000200;
            imgUrl_ = input.readBytes();
            break;
          }
          case 90: {
            if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
              imageUrls_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000400;
            }
            imageUrls_.add(input.readBytes());
            break;
          }
          case 98: {
            if (!((mutable_bitField0_ & 0x00000800) == 0x00000800)) {
              recommendations_ = new java.util.ArrayList<Product>();
              mutable_bitField0_ |= 0x00000800;
            }
            recommendations_.add(input.readMessage(Product.PARSER, extensionRegistry));
            break;
          }
          case 104: {
            bitField0_ |= 0x00000400;
            sellerId_ = input.readUInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
        imageUrls_ = new com.google.protobuf.UnmodifiableLazyStringList(imageUrls_);
      }
      if (((mutable_bitField0_ & 0x00000800) == 0x00000800)) {
        recommendations_ = java.util.Collections.unmodifiableList(recommendations_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProductProtos.internal_static_Product_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProductProtos.internal_static_Product_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Product.class, Product.Builder.class);
  }

  public static com.google.protobuf.Parser<Product> PARSER =
      new com.google.protobuf.AbstractParser<Product>() {
    public Product parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Product(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Product> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional uint64 id = 1;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>optional uint64 id = 1;</code>
   */
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional uint64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  // required string name = 2;
  public static final int NAME_FIELD_NUMBER = 2;
  private java.lang.Object name_;
  /**
   * <code>required string name = 2;</code>
   */
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // required .Brand brand = 3;
  public static final int BRAND_FIELD_NUMBER = 3;
  private Brand brand_;
  /**
   * <code>required .Brand brand = 3;</code>
   */
  public boolean hasBrand() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required .Brand brand = 3;</code>
   */
  public Brand getBrand() {
    return brand_;
  }
  /**
   * <code>required .Brand brand = 3;</code>
   */
  public BrandOrBuilder getBrandOrBuilder() {
    return brand_;
  }

  // required .Category category = 4;
  public static final int CATEGORY_FIELD_NUMBER = 4;
  private Category category_;
  /**
   * <code>required .Category category = 4;</code>
   */
  public boolean hasCategory() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>required .Category category = 4;</code>
   */
  public Category getCategory() {
    return category_;
  }
  /**
   * <code>required .Category category = 4;</code>
   */
  public CategoryOrBuilder getCategoryOrBuilder() {
    return category_;
  }

  // optional string color = 5;
  public static final int COLOR_FIELD_NUMBER = 5;
  private java.lang.Object color_;
  /**
   * <code>optional string color = 5;</code>
   */
  public boolean hasColor() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional string color = 5;</code>
   */
  public java.lang.String getColor() {
    java.lang.Object ref = color_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        color_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string color = 5;</code>
   */
  public com.google.protobuf.ByteString
      getColorBytes() {
    java.lang.Object ref = color_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      color_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // required uint64 sell_rate = 6;
  public static final int SELL_RATE_FIELD_NUMBER = 6;
  private long sellRate_;
  /**
   * <code>required uint64 sell_rate = 6;</code>
   */
  public boolean hasSellRate() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>required uint64 sell_rate = 6;</code>
   */
  public long getSellRate() {
    return sellRate_;
  }

  // required uint64 net_rate = 7;
  public static final int NET_RATE_FIELD_NUMBER = 7;
  private long netRate_;
  /**
   * <code>required uint64 net_rate = 7;</code>
   */
  public boolean hasNetRate() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>required uint64 net_rate = 7;</code>
   */
  public long getNetRate() {
    return netRate_;
  }

  // required uint32 quantity = 8;
  public static final int QUANTITY_FIELD_NUMBER = 8;
  private int quantity_;
  /**
   * <code>required uint32 quantity = 8;</code>
   */
  public boolean hasQuantity() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>required uint32 quantity = 8;</code>
   */
  public int getQuantity() {
    return quantity_;
  }

  // optional string description = 9;
  public static final int DESCRIPTION_FIELD_NUMBER = 9;
  private java.lang.Object description_;
  /**
   * <code>optional string description = 9;</code>
   */
  public boolean hasDescription() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>optional string description = 9;</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        description_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string description = 9;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string imgUrl = 10;
  public static final int IMGURL_FIELD_NUMBER = 10;
  private java.lang.Object imgUrl_;
  /**
   * <code>optional string imgUrl = 10;</code>
   */
  public boolean hasImgUrl() {
    return ((bitField0_ & 0x00000200) == 0x00000200);
  }
  /**
   * <code>optional string imgUrl = 10;</code>
   */
  public java.lang.String getImgUrl() {
    java.lang.Object ref = imgUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        imgUrl_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string imgUrl = 10;</code>
   */
  public com.google.protobuf.ByteString
      getImgUrlBytes() {
    java.lang.Object ref = imgUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      imgUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // repeated string imageUrls = 11;
  public static final int IMAGEURLS_FIELD_NUMBER = 11;
  private com.google.protobuf.LazyStringList imageUrls_;
  /**
   * <code>repeated string imageUrls = 11;</code>
   */
  public java.util.List<java.lang.String>
      getImageUrlsList() {
    return imageUrls_;
  }
  /**
   * <code>repeated string imageUrls = 11;</code>
   */
  public int getImageUrlsCount() {
    return imageUrls_.size();
  }
  /**
   * <code>repeated string imageUrls = 11;</code>
   */
  public java.lang.String getImageUrls(int index) {
    return imageUrls_.get(index);
  }
  /**
   * <code>repeated string imageUrls = 11;</code>
   */
  public com.google.protobuf.ByteString
      getImageUrlsBytes(int index) {
    return imageUrls_.getByteString(index);
  }

  // repeated .Product recommendations = 12;
  public static final int RECOMMENDATIONS_FIELD_NUMBER = 12;
  private java.util.List<Product> recommendations_;
  /**
   * <code>repeated .Product recommendations = 12;</code>
   */
  public java.util.List<Product> getRecommendationsList() {
    return recommendations_;
  }
  /**
   * <code>repeated .Product recommendations = 12;</code>
   */
  public java.util.List<? extends ProductOrBuilder> 
      getRecommendationsOrBuilderList() {
    return recommendations_;
  }
  /**
   * <code>repeated .Product recommendations = 12;</code>
   */
  public int getRecommendationsCount() {
    return recommendations_.size();
  }
  /**
   * <code>repeated .Product recommendations = 12;</code>
   */
  public Product getRecommendations(int index) {
    return recommendations_.get(index);
  }
  /**
   * <code>repeated .Product recommendations = 12;</code>
   */
  public ProductOrBuilder getRecommendationsOrBuilder(
      int index) {
    return recommendations_.get(index);
  }

  // required uint64 seller_id = 13;
  public static final int SELLER_ID_FIELD_NUMBER = 13;
  private long sellerId_;
  /**
   * <code>required uint64 seller_id = 13;</code>
   */
  public boolean hasSellerId() {
    return ((bitField0_ & 0x00000400) == 0x00000400);
  }
  /**
   * <code>required uint64 seller_id = 13;</code>
   */
  public long getSellerId() {
    return sellerId_;
  }

  private void initFields() {
    id_ = 0L;
    name_ = "";
    brand_ = Brand.getDefaultInstance();
    category_ = Category.getDefaultInstance();
    color_ = "";
    sellRate_ = 0L;
    netRate_ = 0L;
    quantity_ = 0;
    description_ = "";
    imgUrl_ = "";
    imageUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    recommendations_ = java.util.Collections.emptyList();
    sellerId_ = 0L;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasBrand()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasCategory()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasSellRate()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasNetRate()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasQuantity()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasSellerId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getBrand().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getCategory().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getRecommendationsCount(); i++) {
      if (!getRecommendations(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeUInt64(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getNameBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeMessage(3, brand_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeMessage(4, category_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(5, getColorBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeUInt64(6, sellRate_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeUInt64(7, netRate_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeUInt32(8, quantity_);
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeBytes(9, getDescriptionBytes());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      output.writeBytes(10, getImgUrlBytes());
    }
    for (int i = 0; i < imageUrls_.size(); i++) {
      output.writeBytes(11, imageUrls_.getByteString(i));
    }
    for (int i = 0; i < recommendations_.size(); i++) {
      output.writeMessage(12, recommendations_.get(i));
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      output.writeUInt64(13, sellerId_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getNameBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, brand_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, category_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, getColorBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, sellRate_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, netRate_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(8, quantity_);
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, getDescriptionBytes());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(10, getImgUrlBytes());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < imageUrls_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(imageUrls_.getByteString(i));
      }
      size += dataSize;
      size += 1 * getImageUrlsList().size();
    }
    for (int i = 0; i < recommendations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, recommendations_.get(i));
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(13, sellerId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static Product parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Product parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Product parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Product parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Product parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static Product parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static Product parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static Product parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static Product parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static Product parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(Product prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Product}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements ProductOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProductProtos.internal_static_Product_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProductProtos.internal_static_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Product.class, Product.Builder.class);
    }

    // Construct using Product.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getBrandFieldBuilder();
        getCategoryFieldBuilder();
        getRecommendationsFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      id_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      if (brandBuilder_ == null) {
        brand_ = Brand.getDefaultInstance();
      } else {
        brandBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (categoryBuilder_ == null) {
        category_ = Category.getDefaultInstance();
      } else {
        categoryBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      color_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      sellRate_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000020);
      netRate_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000040);
      quantity_ = 0;
      bitField0_ = (bitField0_ & ~0x00000080);
      description_ = "";
      bitField0_ = (bitField0_ & ~0x00000100);
      imgUrl_ = "";
      bitField0_ = (bitField0_ & ~0x00000200);
      imageUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000400);
      if (recommendationsBuilder_ == null) {
        recommendations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000800);
      } else {
        recommendationsBuilder_.clear();
      }
      sellerId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00001000);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProductProtos.internal_static_Product_descriptor;
    }

    public Product getDefaultInstanceForType() {
      return Product.getDefaultInstance();
    }

    public Product build() {
      Product result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public Product buildPartial() {
      Product result = new Product(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.id_ = id_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      if (brandBuilder_ == null) {
        result.brand_ = brand_;
      } else {
        result.brand_ = brandBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      if (categoryBuilder_ == null) {
        result.category_ = category_;
      } else {
        result.category_ = categoryBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.color_ = color_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.sellRate_ = sellRate_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.netRate_ = netRate_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      result.quantity_ = quantity_;
      if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
        to_bitField0_ |= 0x00000100;
      }
      result.description_ = description_;
      if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
        to_bitField0_ |= 0x00000200;
      }
      result.imgUrl_ = imgUrl_;
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        imageUrls_ = new com.google.protobuf.UnmodifiableLazyStringList(
            imageUrls_);
        bitField0_ = (bitField0_ & ~0x00000400);
      }
      result.imageUrls_ = imageUrls_;
      if (recommendationsBuilder_ == null) {
        if (((bitField0_ & 0x00000800) == 0x00000800)) {
          recommendations_ = java.util.Collections.unmodifiableList(recommendations_);
          bitField0_ = (bitField0_ & ~0x00000800);
        }
        result.recommendations_ = recommendations_;
      } else {
        result.recommendations_ = recommendationsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
        to_bitField0_ |= 0x00000400;
      }
      result.sellerId_ = sellerId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Product) {
        return mergeFrom((Product)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Product other) {
      if (other == Product.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasBrand()) {
        mergeBrand(other.getBrand());
      }
      if (other.hasCategory()) {
        mergeCategory(other.getCategory());
      }
      if (other.hasColor()) {
        bitField0_ |= 0x00000010;
        color_ = other.color_;
        onChanged();
      }
      if (other.hasSellRate()) {
        setSellRate(other.getSellRate());
      }
      if (other.hasNetRate()) {
        setNetRate(other.getNetRate());
      }
      if (other.hasQuantity()) {
        setQuantity(other.getQuantity());
      }
      if (other.hasDescription()) {
        bitField0_ |= 0x00000100;
        description_ = other.description_;
        onChanged();
      }
      if (other.hasImgUrl()) {
        bitField0_ |= 0x00000200;
        imgUrl_ = other.imgUrl_;
        onChanged();
      }
      if (!other.imageUrls_.isEmpty()) {
        if (imageUrls_.isEmpty()) {
          imageUrls_ = other.imageUrls_;
          bitField0_ = (bitField0_ & ~0x00000400);
        } else {
          ensureImageUrlsIsMutable();
          imageUrls_.addAll(other.imageUrls_);
        }
        onChanged();
      }
      if (recommendationsBuilder_ == null) {
        if (!other.recommendations_.isEmpty()) {
          if (recommendations_.isEmpty()) {
            recommendations_ = other.recommendations_;
            bitField0_ = (bitField0_ & ~0x00000800);
          } else {
            ensureRecommendationsIsMutable();
            recommendations_.addAll(other.recommendations_);
          }
          onChanged();
        }
      } else {
        if (!other.recommendations_.isEmpty()) {
          if (recommendationsBuilder_.isEmpty()) {
            recommendationsBuilder_.dispose();
            recommendationsBuilder_ = null;
            recommendations_ = other.recommendations_;
            bitField0_ = (bitField0_ & ~0x00000800);
            recommendationsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getRecommendationsFieldBuilder() : null;
          } else {
            recommendationsBuilder_.addAllMessages(other.recommendations_);
          }
        }
      }
      if (other.hasSellerId()) {
        setSellerId(other.getSellerId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasName()) {
        
        return false;
      }
      if (!hasBrand()) {
        
        return false;
      }
      if (!hasCategory()) {
        
        return false;
      }
      if (!hasSellRate()) {
        
        return false;
      }
      if (!hasNetRate()) {
        
        return false;
      }
      if (!hasQuantity()) {
        
        return false;
      }
      if (!hasSellerId()) {
        
        return false;
      }
      if (!getBrand().isInitialized()) {
        
        return false;
      }
      if (!getCategory().isInitialized()) {
        
        return false;
      }
      for (int i = 0; i < getRecommendationsCount(); i++) {
        if (!getRecommendations(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Product parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Product) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional uint64 id = 1;
    private long id_ ;
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public Builder setId(long value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    // required string name = 2;
    private java.lang.Object name_ = "";
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 2;</code>
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    // required .Brand brand = 3;
    private Brand brand_ = Brand.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        Brand, Brand.Builder, BrandOrBuilder> brandBuilder_;
    /**
     * <code>required .Brand brand = 3;</code>
     */
    public boolean hasBrand() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .Brand brand = 3;</code>
     */
    public Brand getBrand() {
      if (brandBuilder_ == null) {
        return brand_;
      } else {
        return brandBuilder_.getMessage();
      }
    }
    /**
     * <code>required .Brand brand = 3;</code>
     */
    public Builder setBrand(Brand value) {
      if (brandBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        brand_ = value;
        onChanged();
      } else {
        brandBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>required .Brand brand = 3;</code>
     */
    public Builder setBrand(
        Brand.Builder builderForValue) {
      if (brandBuilder_ == null) {
        brand_ = builderForValue.build();
        onChanged();
      } else {
        brandBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>required .Brand brand = 3;</code>
     */
    public Builder mergeBrand(Brand value) {
      if (brandBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            brand_ != Brand.getDefaultInstance()) {
          brand_ =
            Brand.newBuilder(brand_).mergeFrom(value).buildPartial();
        } else {
          brand_ = value;
        }
        onChanged();
      } else {
        brandBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>required .Brand brand = 3;</code>
     */
    public Builder clearBrand() {
      if (brandBuilder_ == null) {
        brand_ = Brand.getDefaultInstance();
        onChanged();
      } else {
        brandBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>required .Brand brand = 3;</code>
     */
    public Brand.Builder getBrandBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getBrandFieldBuilder().getBuilder();
    }
    /**
     * <code>required .Brand brand = 3;</code>
     */
    public BrandOrBuilder getBrandOrBuilder() {
      if (brandBuilder_ != null) {
        return brandBuilder_.getMessageOrBuilder();
      } else {
        return brand_;
      }
    }
    /**
     * <code>required .Brand brand = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        Brand, Brand.Builder, BrandOrBuilder> 
        getBrandFieldBuilder() {
      if (brandBuilder_ == null) {
        brandBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            Brand, Brand.Builder, BrandOrBuilder>(
                brand_,
                getParentForChildren(),
                isClean());
        brand_ = null;
      }
      return brandBuilder_;
    }

    // required .Category category = 4;
    private Category category_ = Category.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        Category, Category.Builder, CategoryOrBuilder> categoryBuilder_;
    /**
     * <code>required .Category category = 4;</code>
     */
    public boolean hasCategory() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .Category category = 4;</code>
     */
    public Category getCategory() {
      if (categoryBuilder_ == null) {
        return category_;
      } else {
        return categoryBuilder_.getMessage();
      }
    }
    /**
     * <code>required .Category category = 4;</code>
     */
    public Builder setCategory(Category value) {
      if (categoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        category_ = value;
        onChanged();
      } else {
        categoryBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>required .Category category = 4;</code>
     */
    public Builder setCategory(
        Category.Builder builderForValue) {
      if (categoryBuilder_ == null) {
        category_ = builderForValue.build();
        onChanged();
      } else {
        categoryBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>required .Category category = 4;</code>
     */
    public Builder mergeCategory(Category value) {
      if (categoryBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008) &&
            category_ != Category.getDefaultInstance()) {
          category_ =
            Category.newBuilder(category_).mergeFrom(value).buildPartial();
        } else {
          category_ = value;
        }
        onChanged();
      } else {
        categoryBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>required .Category category = 4;</code>
     */
    public Builder clearCategory() {
      if (categoryBuilder_ == null) {
        category_ = Category.getDefaultInstance();
        onChanged();
      } else {
        categoryBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }
    /**
     * <code>required .Category category = 4;</code>
     */
    public Category.Builder getCategoryBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getCategoryFieldBuilder().getBuilder();
    }
    /**
     * <code>required .Category category = 4;</code>
     */
    public CategoryOrBuilder getCategoryOrBuilder() {
      if (categoryBuilder_ != null) {
        return categoryBuilder_.getMessageOrBuilder();
      } else {
        return category_;
      }
    }
    /**
     * <code>required .Category category = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        Category, Category.Builder, CategoryOrBuilder> 
        getCategoryFieldBuilder() {
      if (categoryBuilder_ == null) {
        categoryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            Category, Category.Builder, CategoryOrBuilder>(
                category_,
                getParentForChildren(),
                isClean());
        category_ = null;
      }
      return categoryBuilder_;
    }

    // optional string color = 5;
    private java.lang.Object color_ = "";
    /**
     * <code>optional string color = 5;</code>
     */
    public boolean hasColor() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string color = 5;</code>
     */
    public java.lang.String getColor() {
      java.lang.Object ref = color_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        color_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string color = 5;</code>
     */
    public com.google.protobuf.ByteString
        getColorBytes() {
      java.lang.Object ref = color_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        color_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string color = 5;</code>
     */
    public Builder setColor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      color_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string color = 5;</code>
     */
    public Builder clearColor() {
      bitField0_ = (bitField0_ & ~0x00000010);
      color_ = getDefaultInstance().getColor();
      onChanged();
      return this;
    }
    /**
     * <code>optional string color = 5;</code>
     */
    public Builder setColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      color_ = value;
      onChanged();
      return this;
    }

    // required uint64 sell_rate = 6;
    private long sellRate_ ;
    /**
     * <code>required uint64 sell_rate = 6;</code>
     */
    public boolean hasSellRate() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required uint64 sell_rate = 6;</code>
     */
    public long getSellRate() {
      return sellRate_;
    }
    /**
     * <code>required uint64 sell_rate = 6;</code>
     */
    public Builder setSellRate(long value) {
      bitField0_ |= 0x00000020;
      sellRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint64 sell_rate = 6;</code>
     */
    public Builder clearSellRate() {
      bitField0_ = (bitField0_ & ~0x00000020);
      sellRate_ = 0L;
      onChanged();
      return this;
    }

    // required uint64 net_rate = 7;
    private long netRate_ ;
    /**
     * <code>required uint64 net_rate = 7;</code>
     */
    public boolean hasNetRate() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required uint64 net_rate = 7;</code>
     */
    public long getNetRate() {
      return netRate_;
    }
    /**
     * <code>required uint64 net_rate = 7;</code>
     */
    public Builder setNetRate(long value) {
      bitField0_ |= 0x00000040;
      netRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint64 net_rate = 7;</code>
     */
    public Builder clearNetRate() {
      bitField0_ = (bitField0_ & ~0x00000040);
      netRate_ = 0L;
      onChanged();
      return this;
    }

    // required uint32 quantity = 8;
    private int quantity_ ;
    /**
     * <code>required uint32 quantity = 8;</code>
     */
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required uint32 quantity = 8;</code>
     */
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <code>required uint32 quantity = 8;</code>
     */
    public Builder setQuantity(int value) {
      bitField0_ |= 0x00000080;
      quantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint32 quantity = 8;</code>
     */
    public Builder clearQuantity() {
      bitField0_ = (bitField0_ & ~0x00000080);
      quantity_ = 0;
      onChanged();
      return this;
    }

    // optional string description = 9;
    private java.lang.Object description_ = "";
    /**
     * <code>optional string description = 9;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string description = 9;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string description = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string description = 9;</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string description = 9;</code>
     */
    public Builder clearDescription() {
      bitField0_ = (bitField0_ & ~0x00000100);
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>optional string description = 9;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      description_ = value;
      onChanged();
      return this;
    }

    // optional string imgUrl = 10;
    private java.lang.Object imgUrl_ = "";
    /**
     * <code>optional string imgUrl = 10;</code>
     */
    public boolean hasImgUrl() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string imgUrl = 10;</code>
     */
    public java.lang.String getImgUrl() {
      java.lang.Object ref = imgUrl_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        imgUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string imgUrl = 10;</code>
     */
    public com.google.protobuf.ByteString
        getImgUrlBytes() {
      java.lang.Object ref = imgUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imgUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string imgUrl = 10;</code>
     */
    public Builder setImgUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      imgUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string imgUrl = 10;</code>
     */
    public Builder clearImgUrl() {
      bitField0_ = (bitField0_ & ~0x00000200);
      imgUrl_ = getDefaultInstance().getImgUrl();
      onChanged();
      return this;
    }
    /**
     * <code>optional string imgUrl = 10;</code>
     */
    public Builder setImgUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      imgUrl_ = value;
      onChanged();
      return this;
    }

    // repeated string imageUrls = 11;
    private com.google.protobuf.LazyStringList imageUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureImageUrlsIsMutable() {
      if (!((bitField0_ & 0x00000400) == 0x00000400)) {
        imageUrls_ = new com.google.protobuf.LazyStringArrayList(imageUrls_);
        bitField0_ |= 0x00000400;
       }
    }
    /**
     * <code>repeated string imageUrls = 11;</code>
     */
    public java.util.List<java.lang.String>
        getImageUrlsList() {
      return java.util.Collections.unmodifiableList(imageUrls_);
    }
    /**
     * <code>repeated string imageUrls = 11;</code>
     */
    public int getImageUrlsCount() {
      return imageUrls_.size();
    }
    /**
     * <code>repeated string imageUrls = 11;</code>
     */
    public java.lang.String getImageUrls(int index) {
      return imageUrls_.get(index);
    }
    /**
     * <code>repeated string imageUrls = 11;</code>
     */
    public com.google.protobuf.ByteString
        getImageUrlsBytes(int index) {
      return imageUrls_.getByteString(index);
    }
    /**
     * <code>repeated string imageUrls = 11;</code>
     */
    public Builder setImageUrls(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureImageUrlsIsMutable();
      imageUrls_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imageUrls = 11;</code>
     */
    public Builder addImageUrls(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureImageUrlsIsMutable();
      imageUrls_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imageUrls = 11;</code>
     */
    public Builder addAllImageUrls(
        java.lang.Iterable<java.lang.String> values) {
      ensureImageUrlsIsMutable();
      super.addAll(values, imageUrls_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imageUrls = 11;</code>
     */
    public Builder clearImageUrls() {
      imageUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imageUrls = 11;</code>
     */
    public Builder addImageUrlsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureImageUrlsIsMutable();
      imageUrls_.add(value);
      onChanged();
      return this;
    }

    // repeated .Product recommendations = 12;
    private java.util.List<Product> recommendations_ =
      java.util.Collections.emptyList();
    private void ensureRecommendationsIsMutable() {
      if (!((bitField0_ & 0x00000800) == 0x00000800)) {
        recommendations_ = new java.util.ArrayList<Product>(recommendations_);
        bitField0_ |= 0x00000800;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        Product, Product.Builder, ProductOrBuilder> recommendationsBuilder_;

    /**
     * <code>repeated .Product recommendations = 12;</code>
     */
    public java.util.List<Product> getRecommendationsList() {
      if (recommendationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(recommendations_);
      } else {
        return recommendationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Product recommendations = 12;</code>
     */
    public int getRecommendationsCount() {
      if (recommendationsBuilder_ == null) {
        return recommendations_.size();
      } else {
        return recommendationsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Product recommendations = 12;</code>
     */
    public Product getRecommendations(int index) {
      if (recommendationsBuilder_ == null) {
        return recommendations_.get(index);
      } else {
        return recommendationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Product recommendations = 12;</code>
     */
    public Builder setRecommendations(
        int index, Product value) {
      if (recommendationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecommendationsIsMutable();
        recommendations_.set(index, value);
        onChanged();
      } else {
        recommendationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Product recommendations = 12;</code>
     */
    public Builder setRecommendations(
        int index, Product.Builder builderForValue) {
      if (recommendationsBuilder_ == null) {
        ensureRecommendationsIsMutable();
        recommendations_.set(index, builderForValue.build());
        onChanged();
      } else {
        recommendationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Product recommendations = 12;</code>
     */
    public Builder addRecommendations(Product value) {
      if (recommendationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecommendationsIsMutable();
        recommendations_.add(value);
        onChanged();
      } else {
        recommendationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Product recommendations = 12;</code>
     */
    public Builder addRecommendations(
        int index, Product value) {
      if (recommendationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecommendationsIsMutable();
        recommendations_.add(index, value);
        onChanged();
      } else {
        recommendationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Product recommendations = 12;</code>
     */
    public Builder addRecommendations(
        Product.Builder builderForValue) {
      if (recommendationsBuilder_ == null) {
        ensureRecommendationsIsMutable();
        recommendations_.add(builderForValue.build());
        onChanged();
      } else {
        recommendationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Product recommendations = 12;</code>
     */
    public Builder addRecommendations(
        int index, Product.Builder builderForValue) {
      if (recommendationsBuilder_ == null) {
        ensureRecommendationsIsMutable();
        recommendations_.add(index, builderForValue.build());
        onChanged();
      } else {
        recommendationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Product recommendations = 12;</code>
     */
    public Builder addAllRecommendations(
        java.lang.Iterable<? extends Product> values) {
      if (recommendationsBuilder_ == null) {
        ensureRecommendationsIsMutable();
        super.addAll(values, recommendations_);
        onChanged();
      } else {
        recommendationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Product recommendations = 12;</code>
     */
    public Builder clearRecommendations() {
      if (recommendationsBuilder_ == null) {
        recommendations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000800);
        onChanged();
      } else {
        recommendationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Product recommendations = 12;</code>
     */
    public Builder removeRecommendations(int index) {
      if (recommendationsBuilder_ == null) {
        ensureRecommendationsIsMutable();
        recommendations_.remove(index);
        onChanged();
      } else {
        recommendationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Product recommendations = 12;</code>
     */
    public Product.Builder getRecommendationsBuilder(
        int index) {
      return getRecommendationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Product recommendations = 12;</code>
     */
    public ProductOrBuilder getRecommendationsOrBuilder(
        int index) {
      if (recommendationsBuilder_ == null) {
        return recommendations_.get(index);  } else {
        return recommendationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Product recommendations = 12;</code>
     */
    public java.util.List<? extends ProductOrBuilder> 
         getRecommendationsOrBuilderList() {
      if (recommendationsBuilder_ != null) {
        return recommendationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(recommendations_);
      }
    }
    /**
     * <code>repeated .Product recommendations = 12;</code>
     */
    public Product.Builder addRecommendationsBuilder() {
      return getRecommendationsFieldBuilder().addBuilder(
          Product.getDefaultInstance());
    }
    /**
     * <code>repeated .Product recommendations = 12;</code>
     */
    public Product.Builder addRecommendationsBuilder(
        int index) {
      return getRecommendationsFieldBuilder().addBuilder(
          index, Product.getDefaultInstance());
    }
    /**
     * <code>repeated .Product recommendations = 12;</code>
     */
    public java.util.List<Product.Builder> 
         getRecommendationsBuilderList() {
      return getRecommendationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        Product, Product.Builder, ProductOrBuilder> 
        getRecommendationsFieldBuilder() {
      if (recommendationsBuilder_ == null) {
        recommendationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            Product, Product.Builder, ProductOrBuilder>(
                recommendations_,
                ((bitField0_ & 0x00000800) == 0x00000800),
                getParentForChildren(),
                isClean());
        recommendations_ = null;
      }
      return recommendationsBuilder_;
    }

    // required uint64 seller_id = 13;
    private long sellerId_ ;
    /**
     * <code>required uint64 seller_id = 13;</code>
     */
    public boolean hasSellerId() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>required uint64 seller_id = 13;</code>
     */
    public long getSellerId() {
      return sellerId_;
    }
    /**
     * <code>required uint64 seller_id = 13;</code>
     */
    public Builder setSellerId(long value) {
      bitField0_ |= 0x00001000;
      sellerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint64 seller_id = 13;</code>
     */
    public Builder clearSellerId() {
      bitField0_ = (bitField0_ & ~0x00001000);
      sellerId_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Product)
  }

  static {
    defaultInstance = new Product(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:Product)
}

