// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

/**
 * Protobuf type {@code ProductSearchFilter}
 */
public  final class ProductSearchFilter extends
    com.google.protobuf.GeneratedMessage
    implements ProductSearchFilterOrBuilder {
  // Use ProductSearchFilter.newBuilder() to construct.
  private ProductSearchFilter(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private ProductSearchFilter(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final ProductSearchFilter defaultInstance;
  public static ProductSearchFilter getDefaultInstance() {
    return defaultInstance;
  }

  public ProductSearchFilter getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private ProductSearchFilter(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            brandId_ = input.readUInt64();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            categoryId_ = input.readUInt64();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            businessGroupId_ = input.readUInt64();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            productName_ = input.readUInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProductProtos.internal_static_ProductSearchFilter_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProductProtos.internal_static_ProductSearchFilter_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ProductSearchFilter.class, ProductSearchFilter.Builder.class);
  }

  public static com.google.protobuf.Parser<ProductSearchFilter> PARSER =
      new com.google.protobuf.AbstractParser<ProductSearchFilter>() {
    public ProductSearchFilter parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProductSearchFilter(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<ProductSearchFilter> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional uint64 brand_id = 1;
  public static final int BRAND_ID_FIELD_NUMBER = 1;
  private long brandId_;
  /**
   * <code>optional uint64 brand_id = 1;</code>
   */
  public boolean hasBrandId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional uint64 brand_id = 1;</code>
   */
  public long getBrandId() {
    return brandId_;
  }

  // optional uint64 category_id = 2;
  public static final int CATEGORY_ID_FIELD_NUMBER = 2;
  private long categoryId_;
  /**
   * <code>optional uint64 category_id = 2;</code>
   */
  public boolean hasCategoryId() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional uint64 category_id = 2;</code>
   */
  public long getCategoryId() {
    return categoryId_;
  }

  // optional uint64 business_group_id = 3;
  public static final int BUSINESS_GROUP_ID_FIELD_NUMBER = 3;
  private long businessGroupId_;
  /**
   * <code>optional uint64 business_group_id = 3;</code>
   */
  public boolean hasBusinessGroupId() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional uint64 business_group_id = 3;</code>
   */
  public long getBusinessGroupId() {
    return businessGroupId_;
  }

  // optional uint64 product_name = 4;
  public static final int PRODUCT_NAME_FIELD_NUMBER = 4;
  private long productName_;
  /**
   * <code>optional uint64 product_name = 4;</code>
   */
  public boolean hasProductName() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional uint64 product_name = 4;</code>
   */
  public long getProductName() {
    return productName_;
  }

  private void initFields() {
    brandId_ = 0L;
    categoryId_ = 0L;
    businessGroupId_ = 0L;
    productName_ = 0L;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeUInt64(1, brandId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeUInt64(2, categoryId_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeUInt64(3, businessGroupId_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeUInt64(4, productName_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, brandId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, categoryId_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, businessGroupId_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, productName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static ProductSearchFilter parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProductSearchFilter parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProductSearchFilter parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProductSearchFilter parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProductSearchFilter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ProductSearchFilter parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static ProductSearchFilter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static ProductSearchFilter parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static ProductSearchFilter parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ProductSearchFilter parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(ProductSearchFilter prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ProductSearchFilter}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements ProductSearchFilterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProductProtos.internal_static_ProductSearchFilter_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProductProtos.internal_static_ProductSearchFilter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProductSearchFilter.class, ProductSearchFilter.Builder.class);
    }

    // Construct using ProductSearchFilter.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      brandId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      categoryId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      businessGroupId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      productName_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProductProtos.internal_static_ProductSearchFilter_descriptor;
    }

    public ProductSearchFilter getDefaultInstanceForType() {
      return ProductSearchFilter.getDefaultInstance();
    }

    public ProductSearchFilter build() {
      ProductSearchFilter result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ProductSearchFilter buildPartial() {
      ProductSearchFilter result = new ProductSearchFilter(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.brandId_ = brandId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.categoryId_ = categoryId_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.businessGroupId_ = businessGroupId_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.productName_ = productName_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ProductSearchFilter) {
        return mergeFrom((ProductSearchFilter)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ProductSearchFilter other) {
      if (other == ProductSearchFilter.getDefaultInstance()) return this;
      if (other.hasBrandId()) {
        setBrandId(other.getBrandId());
      }
      if (other.hasCategoryId()) {
        setCategoryId(other.getCategoryId());
      }
      if (other.hasBusinessGroupId()) {
        setBusinessGroupId(other.getBusinessGroupId());
      }
      if (other.hasProductName()) {
        setProductName(other.getProductName());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ProductSearchFilter parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ProductSearchFilter) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional uint64 brand_id = 1;
    private long brandId_ ;
    /**
     * <code>optional uint64 brand_id = 1;</code>
     */
    public boolean hasBrandId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 brand_id = 1;</code>
     */
    public long getBrandId() {
      return brandId_;
    }
    /**
     * <code>optional uint64 brand_id = 1;</code>
     */
    public Builder setBrandId(long value) {
      bitField0_ |= 0x00000001;
      brandId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 brand_id = 1;</code>
     */
    public Builder clearBrandId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      brandId_ = 0L;
      onChanged();
      return this;
    }

    // optional uint64 category_id = 2;
    private long categoryId_ ;
    /**
     * <code>optional uint64 category_id = 2;</code>
     */
    public boolean hasCategoryId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 category_id = 2;</code>
     */
    public long getCategoryId() {
      return categoryId_;
    }
    /**
     * <code>optional uint64 category_id = 2;</code>
     */
    public Builder setCategoryId(long value) {
      bitField0_ |= 0x00000002;
      categoryId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 category_id = 2;</code>
     */
    public Builder clearCategoryId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      categoryId_ = 0L;
      onChanged();
      return this;
    }

    // optional uint64 business_group_id = 3;
    private long businessGroupId_ ;
    /**
     * <code>optional uint64 business_group_id = 3;</code>
     */
    public boolean hasBusinessGroupId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint64 business_group_id = 3;</code>
     */
    public long getBusinessGroupId() {
      return businessGroupId_;
    }
    /**
     * <code>optional uint64 business_group_id = 3;</code>
     */
    public Builder setBusinessGroupId(long value) {
      bitField0_ |= 0x00000004;
      businessGroupId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 business_group_id = 3;</code>
     */
    public Builder clearBusinessGroupId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      businessGroupId_ = 0L;
      onChanged();
      return this;
    }

    // optional uint64 product_name = 4;
    private long productName_ ;
    /**
     * <code>optional uint64 product_name = 4;</code>
     */
    public boolean hasProductName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 product_name = 4;</code>
     */
    public long getProductName() {
      return productName_;
    }
    /**
     * <code>optional uint64 product_name = 4;</code>
     */
    public Builder setProductName(long value) {
      bitField0_ |= 0x00000008;
      productName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 product_name = 4;</code>
     */
    public Builder clearProductName() {
      bitField0_ = (bitField0_ & ~0x00000008);
      productName_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ProductSearchFilter)
  }

  static {
    defaultInstance = new ProductSearchFilter(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:ProductSearchFilter)
}

