// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

public interface ProductSearchFilterOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional uint64 brand_id = 1;
  /**
   * <code>optional uint64 brand_id = 1;</code>
   */
  boolean hasBrandId();
  /**
   * <code>optional uint64 brand_id = 1;</code>
   */
  long getBrandId();

  // optional uint64 category_id = 2;
  /**
   * <code>optional uint64 category_id = 2;</code>
   */
  boolean hasCategoryId();
  /**
   * <code>optional uint64 category_id = 2;</code>
   */
  long getCategoryId();

  // optional uint64 business_group_id = 3;
  /**
   * <code>optional uint64 business_group_id = 3;</code>
   */
  boolean hasBusinessGroupId();
  /**
   * <code>optional uint64 business_group_id = 3;</code>
   */
  long getBusinessGroupId();

  // optional uint64 product_name = 4;
  /**
   * <code>optional uint64 product_name = 4;</code>
   */
  boolean hasProductName();
  /**
   * <code>optional uint64 product_name = 4;</code>
   */
  long getProductName();
}
