// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

public interface ProductSearchRequestOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional .ProductSearchFilter product_search_filter = 1;
  /**
   * <code>optional .ProductSearchFilter product_search_filter = 1;</code>
   */
  boolean hasProductSearchFilter();
  /**
   * <code>optional .ProductSearchFilter product_search_filter = 1;</code>
   */
  ProductSearchFilter getProductSearchFilter();
  /**
   * <code>optional .ProductSearchFilter product_search_filter = 1;</code>
   */
  ProductSearchFilterOrBuilder getProductSearchFilterOrBuilder();

  // repeated uint64 product_id = 2;
  /**
   * <code>repeated uint64 product_id = 2;</code>
   */
  java.util.List<java.lang.Long> getProductIdList();
  /**
   * <code>repeated uint64 product_id = 2;</code>
   */
  int getProductIdCount();
  /**
   * <code>repeated uint64 product_id = 2;</code>
   */
  long getProductId(int index);
}
