// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

public interface RequestedProductOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required uint32 product_id = 1;
  /**
   * <code>required uint32 product_id = 1;</code>
   */
  boolean hasProductId();
  /**
   * <code>required uint32 product_id = 1;</code>
   */
  int getProductId();

  // required uint32 qty = 2;
  /**
   * <code>required uint32 qty = 2;</code>
   */
  boolean hasQty();
  /**
   * <code>required uint32 qty = 2;</code>
   */
  int getQty();
}
