package proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

/**
 * Protobuf type {@code RequestedProduct}
 */
public  final class RequestedProduct extends
    com.google.protobuf.GeneratedMessage
    implements RequestedProductOrBuilder {
  // Use RequestedProduct.newBuilder() to construct.
  private RequestedProduct(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private RequestedProduct(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final RequestedProduct defaultInstance;
  public static RequestedProduct getDefaultInstance() {
    return defaultInstance;
  }

  public RequestedProduct getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private RequestedProduct(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            productId_ = input.readUInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            qty_ = input.readUInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProductProtos.internal_static_RequestedProduct_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProductProtos.internal_static_RequestedProduct_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RequestedProduct.class, RequestedProduct.Builder.class);
  }

  public static com.google.protobuf.Parser<RequestedProduct> PARSER =
      new com.google.protobuf.AbstractParser<RequestedProduct>() {
    public RequestedProduct parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestedProduct(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<RequestedProduct> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required uint32 product_id = 1;
  public static final int PRODUCT_ID_FIELD_NUMBER = 1;
  private int productId_;
  /**
   * <code>required uint32 product_id = 1;</code>
   */
  public boolean hasProductId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required uint32 product_id = 1;</code>
   */
  public int getProductId() {
    return productId_;
  }

  // required uint32 qty = 2;
  public static final int QTY_FIELD_NUMBER = 2;
  private int qty_;
  /**
   * <code>required uint32 qty = 2;</code>
   */
  public boolean hasQty() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required uint32 qty = 2;</code>
   */
  public int getQty() {
    return qty_;
  }

  private void initFields() {
    productId_ = 0;
    qty_ = 0;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasProductId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasQty()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeUInt32(1, productId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeUInt32(2, qty_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, productId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, qty_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static RequestedProduct parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RequestedProduct parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RequestedProduct parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RequestedProduct parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RequestedProduct parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static RequestedProduct parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static RequestedProduct parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static RequestedProduct parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static RequestedProduct parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static RequestedProduct parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(RequestedProduct prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RequestedProduct}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements RequestedProductOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProductProtos.internal_static_RequestedProduct_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProductProtos.internal_static_RequestedProduct_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestedProduct.class, RequestedProduct.Builder.class);
    }

    // Construct using RequestedProduct.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      productId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      qty_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProductProtos.internal_static_RequestedProduct_descriptor;
    }

    public RequestedProduct getDefaultInstanceForType() {
      return RequestedProduct.getDefaultInstance();
    }

    public RequestedProduct build() {
      RequestedProduct result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public RequestedProduct buildPartial() {
      RequestedProduct result = new RequestedProduct(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.productId_ = productId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.qty_ = qty_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RequestedProduct) {
        return mergeFrom((RequestedProduct)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RequestedProduct other) {
      if (other == RequestedProduct.getDefaultInstance()) return this;
      if (other.hasProductId()) {
        setProductId(other.getProductId());
      }
      if (other.hasQty()) {
        setQty(other.getQty());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasProductId()) {
        
        return false;
      }
      if (!hasQty()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      RequestedProduct parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (RequestedProduct) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required uint32 product_id = 1;
    private int productId_ ;
    /**
     * <code>required uint32 product_id = 1;</code>
     */
    public boolean hasProductId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 product_id = 1;</code>
     */
    public int getProductId() {
      return productId_;
    }
    /**
     * <code>required uint32 product_id = 1;</code>
     */
    public Builder setProductId(int value) {
      bitField0_ |= 0x00000001;
      productId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint32 product_id = 1;</code>
     */
    public Builder clearProductId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      productId_ = 0;
      onChanged();
      return this;
    }

    // required uint32 qty = 2;
    private int qty_ ;
    /**
     * <code>required uint32 qty = 2;</code>
     */
    public boolean hasQty() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 qty = 2;</code>
     */
    public int getQty() {
      return qty_;
    }
    /**
     * <code>required uint32 qty = 2;</code>
     */
    public Builder setQty(int value) {
      bitField0_ |= 0x00000002;
      qty_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint32 qty = 2;</code>
     */
    public Builder clearQty() {
      bitField0_ = (bitField0_ & ~0x00000002);
      qty_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:RequestedProduct)
  }

  static {
    defaultInstance = new RequestedProduct(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:RequestedProduct)
}

