package proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

/**
 * Protobuf type {@code ProductCheckoutResponse}
 */
public  final class ProductCheckoutResponse extends
    com.google.protobuf.GeneratedMessage
    implements ProductCheckoutResponseOrBuilder {
  // Use ProductCheckoutResponse.newBuilder() to construct.
  private ProductCheckoutResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private ProductCheckoutResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final ProductCheckoutResponse defaultInstance;
  public static ProductCheckoutResponse getDefaultInstance() {
    return defaultInstance;
  }

  public ProductCheckoutResponse getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private ProductCheckoutResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              orderDetail_ = new java.util.ArrayList<OrderDetail>();
              mutable_bitField0_ |= 0x00000001;
            }
            orderDetail_.add(input.readMessage(OrderDetail.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        orderDetail_ = java.util.Collections.unmodifiableList(orderDetail_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProductProtos.internal_static_ProductCheckoutResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProductProtos.internal_static_ProductCheckoutResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ProductCheckoutResponse.class, ProductCheckoutResponse.Builder.class);
  }

  public static com.google.protobuf.Parser<ProductCheckoutResponse> PARSER =
      new com.google.protobuf.AbstractParser<ProductCheckoutResponse>() {
    public ProductCheckoutResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProductCheckoutResponse(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<ProductCheckoutResponse> getParserForType() {
    return PARSER;
  }

  // repeated .OrderDetail order_detail = 1;
  public static final int ORDER_DETAIL_FIELD_NUMBER = 1;
  private java.util.List<OrderDetail> orderDetail_;
  /**
   * <code>repeated .OrderDetail order_detail = 1;</code>
   */
  public java.util.List<OrderDetail> getOrderDetailList() {
    return orderDetail_;
  }
  /**
   * <code>repeated .OrderDetail order_detail = 1;</code>
   */
  public java.util.List<? extends OrderDetailOrBuilder> 
      getOrderDetailOrBuilderList() {
    return orderDetail_;
  }
  /**
   * <code>repeated .OrderDetail order_detail = 1;</code>
   */
  public int getOrderDetailCount() {
    return orderDetail_.size();
  }
  /**
   * <code>repeated .OrderDetail order_detail = 1;</code>
   */
  public OrderDetail getOrderDetail(int index) {
    return orderDetail_.get(index);
  }
  /**
   * <code>repeated .OrderDetail order_detail = 1;</code>
   */
  public OrderDetailOrBuilder getOrderDetailOrBuilder(
      int index) {
    return orderDetail_.get(index);
  }

  private void initFields() {
    orderDetail_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    for (int i = 0; i < getOrderDetailCount(); i++) {
      if (!getOrderDetail(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < orderDetail_.size(); i++) {
      output.writeMessage(1, orderDetail_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < orderDetail_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, orderDetail_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static ProductCheckoutResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProductCheckoutResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProductCheckoutResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProductCheckoutResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProductCheckoutResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ProductCheckoutResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static ProductCheckoutResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static ProductCheckoutResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static ProductCheckoutResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ProductCheckoutResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(ProductCheckoutResponse prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ProductCheckoutResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements ProductCheckoutResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProductProtos.internal_static_ProductCheckoutResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProductProtos.internal_static_ProductCheckoutResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProductCheckoutResponse.class, ProductCheckoutResponse.Builder.class);
    }

    // Construct using ProductCheckoutResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getOrderDetailFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (orderDetailBuilder_ == null) {
        orderDetail_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        orderDetailBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProductProtos.internal_static_ProductCheckoutResponse_descriptor;
    }

    public ProductCheckoutResponse getDefaultInstanceForType() {
      return ProductCheckoutResponse.getDefaultInstance();
    }

    public ProductCheckoutResponse build() {
      ProductCheckoutResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ProductCheckoutResponse buildPartial() {
      ProductCheckoutResponse result = new ProductCheckoutResponse(this);
      int from_bitField0_ = bitField0_;
      if (orderDetailBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          orderDetail_ = java.util.Collections.unmodifiableList(orderDetail_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.orderDetail_ = orderDetail_;
      } else {
        result.orderDetail_ = orderDetailBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ProductCheckoutResponse) {
        return mergeFrom((ProductCheckoutResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ProductCheckoutResponse other) {
      if (other == ProductCheckoutResponse.getDefaultInstance()) return this;
      if (orderDetailBuilder_ == null) {
        if (!other.orderDetail_.isEmpty()) {
          if (orderDetail_.isEmpty()) {
            orderDetail_ = other.orderDetail_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOrderDetailIsMutable();
            orderDetail_.addAll(other.orderDetail_);
          }
          onChanged();
        }
      } else {
        if (!other.orderDetail_.isEmpty()) {
          if (orderDetailBuilder_.isEmpty()) {
            orderDetailBuilder_.dispose();
            orderDetailBuilder_ = null;
            orderDetail_ = other.orderDetail_;
            bitField0_ = (bitField0_ & ~0x00000001);
            orderDetailBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getOrderDetailFieldBuilder() : null;
          } else {
            orderDetailBuilder_.addAllMessages(other.orderDetail_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      for (int i = 0; i < getOrderDetailCount(); i++) {
        if (!getOrderDetail(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ProductCheckoutResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ProductCheckoutResponse) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // repeated .OrderDetail order_detail = 1;
    private java.util.List<OrderDetail> orderDetail_ =
      java.util.Collections.emptyList();
    private void ensureOrderDetailIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        orderDetail_ = new java.util.ArrayList<OrderDetail>(orderDetail_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        OrderDetail, OrderDetail.Builder, OrderDetailOrBuilder> orderDetailBuilder_;

    /**
     * <code>repeated .OrderDetail order_detail = 1;</code>
     */
    public java.util.List<OrderDetail> getOrderDetailList() {
      if (orderDetailBuilder_ == null) {
        return java.util.Collections.unmodifiableList(orderDetail_);
      } else {
        return orderDetailBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .OrderDetail order_detail = 1;</code>
     */
    public int getOrderDetailCount() {
      if (orderDetailBuilder_ == null) {
        return orderDetail_.size();
      } else {
        return orderDetailBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .OrderDetail order_detail = 1;</code>
     */
    public OrderDetail getOrderDetail(int index) {
      if (orderDetailBuilder_ == null) {
        return orderDetail_.get(index);
      } else {
        return orderDetailBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .OrderDetail order_detail = 1;</code>
     */
    public Builder setOrderDetail(
        int index, OrderDetail value) {
      if (orderDetailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderDetailIsMutable();
        orderDetail_.set(index, value);
        onChanged();
      } else {
        orderDetailBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .OrderDetail order_detail = 1;</code>
     */
    public Builder setOrderDetail(
        int index, OrderDetail.Builder builderForValue) {
      if (orderDetailBuilder_ == null) {
        ensureOrderDetailIsMutable();
        orderDetail_.set(index, builderForValue.build());
        onChanged();
      } else {
        orderDetailBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OrderDetail order_detail = 1;</code>
     */
    public Builder addOrderDetail(OrderDetail value) {
      if (orderDetailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderDetailIsMutable();
        orderDetail_.add(value);
        onChanged();
      } else {
        orderDetailBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .OrderDetail order_detail = 1;</code>
     */
    public Builder addOrderDetail(
        int index, OrderDetail value) {
      if (orderDetailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderDetailIsMutable();
        orderDetail_.add(index, value);
        onChanged();
      } else {
        orderDetailBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .OrderDetail order_detail = 1;</code>
     */
    public Builder addOrderDetail(
        OrderDetail.Builder builderForValue) {
      if (orderDetailBuilder_ == null) {
        ensureOrderDetailIsMutable();
        orderDetail_.add(builderForValue.build());
        onChanged();
      } else {
        orderDetailBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OrderDetail order_detail = 1;</code>
     */
    public Builder addOrderDetail(
        int index, OrderDetail.Builder builderForValue) {
      if (orderDetailBuilder_ == null) {
        ensureOrderDetailIsMutable();
        orderDetail_.add(index, builderForValue.build());
        onChanged();
      } else {
        orderDetailBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OrderDetail order_detail = 1;</code>
     */
    public Builder addAllOrderDetail(
        java.lang.Iterable<? extends OrderDetail> values) {
      if (orderDetailBuilder_ == null) {
        ensureOrderDetailIsMutable();
        super.addAll(values, orderDetail_);
        onChanged();
      } else {
        orderDetailBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .OrderDetail order_detail = 1;</code>
     */
    public Builder clearOrderDetail() {
      if (orderDetailBuilder_ == null) {
        orderDetail_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        orderDetailBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .OrderDetail order_detail = 1;</code>
     */
    public Builder removeOrderDetail(int index) {
      if (orderDetailBuilder_ == null) {
        ensureOrderDetailIsMutable();
        orderDetail_.remove(index);
        onChanged();
      } else {
        orderDetailBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .OrderDetail order_detail = 1;</code>
     */
    public OrderDetail.Builder getOrderDetailBuilder(
        int index) {
      return getOrderDetailFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .OrderDetail order_detail = 1;</code>
     */
    public OrderDetailOrBuilder getOrderDetailOrBuilder(
        int index) {
      if (orderDetailBuilder_ == null) {
        return orderDetail_.get(index);  } else {
        return orderDetailBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .OrderDetail order_detail = 1;</code>
     */
    public java.util.List<? extends OrderDetailOrBuilder> 
         getOrderDetailOrBuilderList() {
      if (orderDetailBuilder_ != null) {
        return orderDetailBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(orderDetail_);
      }
    }
    /**
     * <code>repeated .OrderDetail order_detail = 1;</code>
     */
    public OrderDetail.Builder addOrderDetailBuilder() {
      return getOrderDetailFieldBuilder().addBuilder(
          OrderDetail.getDefaultInstance());
    }
    /**
     * <code>repeated .OrderDetail order_detail = 1;</code>
     */
    public OrderDetail.Builder addOrderDetailBuilder(
        int index) {
      return getOrderDetailFieldBuilder().addBuilder(
          index, OrderDetail.getDefaultInstance());
    }
    /**
     * <code>repeated .OrderDetail order_detail = 1;</code>
     */
    public java.util.List<OrderDetail.Builder> 
         getOrderDetailBuilderList() {
      return getOrderDetailFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        OrderDetail, OrderDetail.Builder, OrderDetailOrBuilder> 
        getOrderDetailFieldBuilder() {
      if (orderDetailBuilder_ == null) {
        orderDetailBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            OrderDetail, OrderDetail.Builder, OrderDetailOrBuilder>(
                orderDetail_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        orderDetail_ = null;
      }
      return orderDetailBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:ProductCheckoutResponse)
  }

  static {
    defaultInstance = new ProductCheckoutResponse(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:ProductCheckoutResponse)
}

