package proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

public interface ProductCheckoutResponseOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // repeated .OrderDetail order_detail = 1;
  /**
   * <code>repeated .OrderDetail order_detail = 1;</code>
   */
  java.util.List<OrderDetail> 
      getOrderDetailList();
  /**
   * <code>repeated .OrderDetail order_detail = 1;</code>
   */
  OrderDetail getOrderDetail(int index);
  /**
   * <code>repeated .OrderDetail order_detail = 1;</code>
   */
  int getOrderDetailCount();
  /**
   * <code>repeated .OrderDetail order_detail = 1;</code>
   */
  java.util.List<? extends OrderDetailOrBuilder> 
      getOrderDetailOrBuilderList();
  /**
   * <code>repeated .OrderDetail order_detail = 1;</code>
   */
  OrderDetailOrBuilder getOrderDetailOrBuilder(
      int index);
}
