package proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

public interface ProductOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional uint64 id = 1;
  /**
   * <code>optional uint64 id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>optional uint64 id = 1;</code>
   */
  long getId();

  // required string name = 2;
  /**
   * <code>required string name = 2;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  // required .Brand brand = 3;
  /**
   * <code>required .Brand brand = 3;</code>
   */
  boolean hasBrand();
  /**
   * <code>required .Brand brand = 3;</code>
   */
  Brand getBrand();
  /**
   * <code>required .Brand brand = 3;</code>
   */
  BrandOrBuilder getBrandOrBuilder();

  // required .Category category = 4;
  /**
   * <code>required .Category category = 4;</code>
   */
  boolean hasCategory();
  /**
   * <code>required .Category category = 4;</code>
   */
  Category getCategory();
  /**
   * <code>required .Category category = 4;</code>
   */
  CategoryOrBuilder getCategoryOrBuilder();

  // optional string color = 5;
  /**
   * <code>optional string color = 5;</code>
   */
  boolean hasColor();
  /**
   * <code>optional string color = 5;</code>
   */
  java.lang.String getColor();
  /**
   * <code>optional string color = 5;</code>
   */
  com.google.protobuf.ByteString
      getColorBytes();

  // required uint64 sell_rate = 6;
  /**
   * <code>required uint64 sell_rate = 6;</code>
   */
  boolean hasSellRate();
  /**
   * <code>required uint64 sell_rate = 6;</code>
   */
  long getSellRate();

  // required uint64 net_rate = 7;
  /**
   * <code>required uint64 net_rate = 7;</code>
   */
  boolean hasNetRate();
  /**
   * <code>required uint64 net_rate = 7;</code>
   */
  long getNetRate();

  // required uint32 quantity = 8;
  /**
   * <code>required uint32 quantity = 8;</code>
   */
  boolean hasQuantity();
  /**
   * <code>required uint32 quantity = 8;</code>
   */
  int getQuantity();

  // optional string description = 9;
  /**
   * <code>optional string description = 9;</code>
   */
  boolean hasDescription();
  /**
   * <code>optional string description = 9;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 9;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  // optional string imgUrl = 10;
  /**
   * <code>optional string imgUrl = 10;</code>
   */
  boolean hasImgUrl();
  /**
   * <code>optional string imgUrl = 10;</code>
   */
  java.lang.String getImgUrl();
  /**
   * <code>optional string imgUrl = 10;</code>
   */
  com.google.protobuf.ByteString
      getImgUrlBytes();

  // repeated string imageUrls = 11;
  /**
   * <code>repeated string imageUrls = 11;</code>
   */
  java.util.List<java.lang.String>
  getImageUrlsList();
  /**
   * <code>repeated string imageUrls = 11;</code>
   */
  int getImageUrlsCount();
  /**
   * <code>repeated string imageUrls = 11;</code>
   */
  java.lang.String getImageUrls(int index);
  /**
   * <code>repeated string imageUrls = 11;</code>
   */
  com.google.protobuf.ByteString
      getImageUrlsBytes(int index);

  // repeated .Product recommendations = 12;
  /**
   * <code>repeated .Product recommendations = 12;</code>
   */
  java.util.List<Product> 
      getRecommendationsList();
  /**
   * <code>repeated .Product recommendations = 12;</code>
   */
  Product getRecommendations(int index);
  /**
   * <code>repeated .Product recommendations = 12;</code>
   */
  int getRecommendationsCount();
  /**
   * <code>repeated .Product recommendations = 12;</code>
   */
  java.util.List<? extends ProductOrBuilder> 
      getRecommendationsOrBuilderList();
  /**
   * <code>repeated .Product recommendations = 12;</code>
   */
  ProductOrBuilder getRecommendationsOrBuilder(
      int index);

  // required uint64 seller_id = 13;
  /**
   * <code>required uint64 seller_id = 13;</code>
   */
  boolean hasSellerId();
  /**
   * <code>required uint64 seller_id = 13;</code>
   */
  long getSellerId();
}
